# compose.yaml
services:
  app_data_generator:
    depends_on:
      influxdb:
        condition: service_started
    env_file:
      - ../src/.env
    build:
      context: ../
      dockerfile: docker/config/app_data_generator/Dockerfile
      args:
        - VERSION="0.0.1"
        - BUILD_DATE="2025-04-27"
    container_name: app_data_generator
    networks:
      - local_lab_net
  influxdb:
    image: influxdb:1.8.3-alpine
    container_name: influxdb
    ports:
      - 8086:8086
    restart: none
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb-admin-token
      DOCKER_INFLUXDB_INIT_ORG: local_lab
      DOCKER_INFLUXDB_INIT_BUCKET: temp_sensor
    secrets:
      - influxdb-admin-username
      - influxdb-admin-password
      - influxdb-admin-token
    volumes:
      - type: volume
        source: influxdb-data
        target: /var/lib/influxdb
      - type: volume
        source: influxdb-config
        target: /etc/influxdb
    networks:
      - local_lab_net
  grafana:
    image: grafana/grafana:11.3.0
    container_name: grafana
    restart: none
    environment:
     - GF_SERVER_ROOT_URL=http://my.grafana.server/
     - GF_INSTALL_PLUGINS=grafana-clock-panel
    ports:
     - '3000:3000'
    volumes:
     - './config/grafana:/etc/grafana'
     - 'grafana-storage:/var/lib/grafana'
    networks:
      - local_lab_net
  mailpit:
    image: axllent/mailpit:v1.24 
    container_name: mailpit
    restart: none
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - local_lab_net
secrets:
  influxdb-admin-username:
    file: .env/influxdb-admin-username
  influxdb-admin-password:
    file: .env/influxdb-admin-password
  influxdb-admin-token:
    file: .env/influxdb-admin-token
volumes:
  influxdb-data:
  influxdb-config:
  grafana-storage: {}
networks:
  local_lab_net:
    driver: bridge